/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      fontFamily: {
        display: ['"Nunito"', 'system-ui', 'sans-serif'],
        body:    ['"Nunito"', 'system-ui', 'sans-serif'],
        mono:    ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      colors: {
        brand: {
          purple:  '#7C3AED',
          violet:  '#6D28D9',
          pink:    '#EC4899',
          cyan:    '#06B6D4',
          yellow:  '#F59E0B',
          green:   '#10B981',
          red:     '#EF4444',
          orange:  '#F97316',
        },
      },
      animation: {
        'float':        'float 6s ease-in-out infinite',
        'float-r':      'floatR 7s ease-in-out infinite',
        'glow-pulse':   'glowPulse 3s ease-in-out infinite',
        'slide-up':     'slideUp 0.5s cubic-bezier(0.16,1,0.3,1) both',
        'slide-down':   'slideDown 0.4s cubic-bezier(0.16,1,0.3,1) both',
        'scale-in':     'scaleIn 0.4s cubic-bezier(0.34,1.56,0.64,1) both',
        'fade-in':      'fadeIn 0.3s ease both',
        'shake':        'shake 0.4s ease-in-out',
        'jelly':        'jelly 0.5s ease-in-out',
        'tada':         'tada 0.6s ease-in-out',
        'wiggle':       'wiggle 0.4s ease-in-out',
        'spin-slow':    'spin 4s linear infinite',
        'pulse-soft':   'pulseSoft 2s ease-in-out infinite',
        'score-up':     'scoreUp 0.5s cubic-bezier(0.34,1.56,0.64,1) both',
        'ripple':       'ripple 0.6s ease-out',
        'star-twinkle': 'starTwinkle 3s ease-in-out infinite',
        'drift':        'drift 20s ease-in-out infinite',
      },
      keyframes: {
        float:       { '0%,100%': { transform: 'translateY(0px) rotate(0deg)' }, '33%': { transform: 'translateY(-14px) rotate(1deg)' }, '66%': { transform: 'translateY(-7px) rotate(-1deg)' } },
        floatR:      { '0%,100%': { transform: 'translateY(0px) rotate(0deg)' }, '33%': { transform: 'translateY(-10px) rotate(-1.5deg)' }, '66%': { transform: 'translateY(-18px) rotate(1deg)' } },
        glowPulse:   { '0%,100%': { opacity: '0.6' }, '50%': { opacity: '1' } },
        slideUp:     { from: { opacity: '0', transform: 'translateY(32px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        slideDown:   { from: { opacity: '0', transform: 'translateY(-16px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        scaleIn:     { from: { opacity: '0', transform: 'scale(0.6)' }, to: { opacity: '1', transform: 'scale(1)' } },
        fadeIn:      { from: { opacity: '0' }, to: { opacity: '1' } },
        shake:       { '0%,100%': { transform: 'translateX(0)' }, '20%': { transform: 'translateX(-8px)' }, '40%': { transform: 'translateX(8px)' }, '60%': { transform: 'translateX(-5px)' }, '80%': { transform: 'translateX(5px)' } },
        jelly:       { '0%,100%': { transform: 'scale(1,1)' }, '30%': { transform: 'scale(1.1,0.9)' }, '60%': { transform: 'scale(0.95,1.05)' }, '80%': { transform: 'scale(1.02,0.98)' } },
        tada:        { '0%': { transform: 'scale(1)' }, '10%,20%': { transform: 'scale(0.9) rotate(-8deg)' }, '30%,50%,70%,90%': { transform: 'scale(1.15) rotate(6deg)' }, '40%,60%,80%': { transform: 'scale(1.15) rotate(-6deg)' }, '100%': { transform: 'scale(1)' } },
        wiggle:      { '0%,100%': { transform: 'rotate(-4deg)' }, '50%': { transform: 'rotate(4deg)' } },
        pulseSoft:   { '0%,100%': { opacity: '1' }, '50%': { opacity: '0.6' } },
        scoreUp:     { from: { opacity: '0', transform: 'scale(0.5) translateY(10px)' }, to: { opacity: '1', transform: 'scale(1) translateY(0)' } },
        ripple:      { from: { transform: 'scale(0)', opacity: '0.6' }, to: { transform: 'scale(4)', opacity: '0' } },
        starTwinkle: { '0%,100%': { opacity: '0.15', transform: 'scale(0.8)' }, '50%': { opacity: '0.9', transform: 'scale(1.2)' } },
        shimmer:     { '0%': { transform: 'translateX(-100%)' }, '100%': { transform: 'translateX(300%)' } },
        drift:       { '0%,100%': { transform: 'translate(0,0) rotate(0deg)' }, '25%': { transform: 'translate(30px,-20px) rotate(90deg)' }, '50%': { transform: 'translate(-10px,-40px) rotate(180deg)' }, '75%': { transform: 'translate(-30px,-10px) rotate(270deg)' } },
      },
    },
  },
  plugins: [],
}
